version: "3"
services:
  nginx:
    image: "sagi403/ltl-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  backend:
    image: "sagi403/ltl-backend"
    mem_limit: 128m
    hostname: backend
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - URL=$URL
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL=$EMAIL
      - PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
  frontend:
    image: "sagi403/ltl-frontend"
    mem_limit: 128m
    hostname: frontend
