import { Container } from "react-bootstrap";
import Meta from "../components/Meta";

const PrivacyPolicyScreen = () => {
  return (
    <Container className="my-5">
      <Meta title="Privacy Policy" />
      <h1>Privacy Policy</h1>
      <p>
        This Privacy Policy describes how your personal information is
        collected, used, and shared when you visit or make a purchase from
        love-that-last.shop (the “Site”).
      </p>
      <h4 className="mt-4">Personal information we collect</h4>
      <p>
        When you visit the Site, we automatically collect certain information
        about your device, including information about your web browser, IP
        address, time zone, and some of the cookies that are installed on your
        device. Additionally, as you browse the Site, we collect information
        about the individual web pages or products that you view, what websites
        or search terms referred you to the Site, and information about how you
        interact with the Site. We refer to this automatically-collected
        information as “Device Information”.
      </p>
      <p>We collect Device Information using the following technologies:</p>
      <ul>
        <li>
          “Cookies” are data files that are placed on your device or computer
          and often include an anonymous unique identifier. For more information
          about cookies, and how to disable cookies, visit
          http://www.allaboutcookies.org.
        </li>
        <li>
          “Log files” track actions occurring on the Site, and collect data
          including your IP address, browser type, Internet service provider,
          referring/exit pages, and date/time stamps.
        </li>
        <li>
          “Web beacons”, “tags”, and “pixels” are electronic files used to
          record information about how you browse the Site.
        </li>
      </ul>
      <p>
        Additionally when you make a purchase or attempt to make a purchase
        through the Site, we collect certain information from you, including
        your name, billing address, shipping address, payment information
        (including credit card numbers), email address, and phone number. We
        refer to this information as “Order Information”.
      </p>
      <p>
        In our shop we use functions of the web analysis service Google
        Analytics. The provider is Google Inc, 1600 Amphitheatre Parkway,
        Mountain View, CA 94043, USA. Google Analytics uses so-called "cookies".
        These are text files that are stored on your computer and enable an
        analysis of your use of the website. The information about your use of
        this website, which is generated by the cookie, is usually transferred
        to a Google server in the USA and stored there.
      </p>
      <p>
        When we talk about “Personal Information” in this Privacy Policy, we are
        talking both about Device Information and Order Information.
      </p>
      <h4 className="mt-4">How do we use your personal information?</h4>
      <p>
        We use the Order Information that we collect generally to fulfill any
        orders placed through the Site (including processing your payment
        information, arranging for shipping, and providing you with invoices
        and/or order confirmations). Additionally, we use this Order Information
        to:
      </p>
      <ul>
        <li>Communicate with you;</li>
        <li>Screen our orders for potential risk or fraud; and</li>
        <li>
          When in line with the preferences you have shared with us, provide you
          with information or advertising relating to our products or services.
        </li>
      </ul>
      <p>
        The Google Analytics cookie (legal basis Art. 6 (1) (f) GDPR) is stored
        on the basis of our legitimate interest in the analysis of user’s
        behavior in order to optimize our Internet offer and our advertising. We
        are supported by Google as a service provider. Google will use this
        information to evaluate, how the user use our website, to compile
        reports on the website activities and to provide the website operator
        with further services associated with the use of the website and the
        Internet. The IP address transmitted by your browser in the context of
        Google Analytics is not merged with other Google data.
      </p>
      <p>
        We use the Device Information that we collect to help us screen for
        potential risk and fraud (in particular, your IP address), and more
        generally to improve and optimize our Site (for example, by generating
        analytics about how our customers browse and interact with the Site, and
        to assess the success of our marketing and advertising campaigns).{" "}
      </p>
      <p>
        Retargeting - We use functions to encourage our website visitors to buy
        already viewed products (legal basis: Art. 6 (1) (f) GDPR). Our
        legitimate interest is to advertise the sale of our products. The IP
        address is anonymized within 24 hours. All other data will be
        pseudonymised immediately and deleted when the processing purpose
        ceases. You can object to this processing at any time.
      </p>
      <p>
        With your explicit consent, which can be revoked at any time, we inform
        you by e-mail about our products and promotions such as campaigns and
        events in our shop and/or about our various product newsletters. When
        you give your consent, we process your mandatory data in order to send
        you the newsletter(s) you have chosen and to address you personally
        (Art. 6 (1) (f) GDPR). To receive certain newsletters, you first have to
        register. When obtaining your consent, we use online the so-called
        double opt-in procedure to prevent our e-mail messages being sent to
        e-mail addresses of persons who have not requested them or do not wish
        to receive them. Your IP address is also recorded and stored for
        documentation purposes in accordance with the requirements of the data
        protection supervisory authorities. (Art. 7 (1), Art. 6 (1) (c) GPDR).
        If you provided us with your e-mail address when you registered or
        ordered, we will also inform you by e-mail about our products, which are
        similar to those you purchased. You can of course object to this at any
        time at basic rates. We store your data collected for advertising
        purposes as long as the advertising purpose exists or until we receive a
        revocation of your consent or your objection to the processing of your
        data for advertising purposes.
      </p>
      <h4 className="mt-4">Sharing you personal Information</h4>
      <p>
        We share your Personal Information with third parties to help us use
        your Personal Information, as described above. We use Google Analytics
        to help us understand how our customers use the Site -- you can read
        more about how Google uses your Personal Information here:
        https://www.google.com/intl/en/policies/privacy/. You can also opt-out
        of Google Analytics here: https://tools.google.com/dlpage/gaoptout.
      </p>
      <p>
        Finally, we may also share your Personal Information to comply with
        applicable laws and regulations, to respond to a subpoena, search
        warrant or other lawful request for information we receive, or to
        otherwise protect our rights.
      </p>
      <h4 className="mt-4">Behavioural advertising</h4>
      <p>
        As described above, we use your Personal Information to provide you with
        targeted advertisements or marketing communications we believe may be of
        interest to you. For more information about how targeted advertising
        works, you can visit the Network Advertising Initiative’s (“NAI”)
        educational page at
        http://www.networkadvertising.org/understanding-online-advertising/how-does-it-work.
      </p>
      <p>You can opt out of targeted advertising by using the links below:</p>
      <ul>
        <li>Facebook: https://www.facebook.com/settings/?tab=ads</li>
        <li>Google: https://www.google.com/settings/ads/anonymous</li>
        <li>
          Bing:
          https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads{" "}
        </li>
        <li>
          Pintrest:
          https://help.pinterest.com/en/article/want-to-stop-receiving-email
        </li>
      </ul>
      <p>
        Additionally, you can opt out of some of these services by visiting the
        Digital Advertising Alliance’s opt-out portal at:
        http://optout.aboutads.info/.
      </p>
      <h4 className="mt-4">Do not track</h4>
      <p>
        Please note that we do not alter our Site’s data collection and use
        practices when we see a Do Not Track signal from your browser.
      </p>
      <h4 className="mt-4">Your rights</h4>
      <p>
        If you are a European resident, you have the right to access personal
        information we hold about you and to ask that your personal information
        be corrected, updated, or deleted. If you would like to exercise this
        right, please contact us through the contact information below.
      </p>
      <p>
        Additionally, if you are a European resident we note that we are
        processing your information in order to fulfill contracts we might have
        with you (for example if you make an order through the Site), or
        otherwise to pursue our legitimate business interests listed above.
        Additionally, please note that your information will be transferred
        outside of Europe, including to Canada and the United States.
      </p>
      <h4 className="mt-4">Data retention</h4>
      <p>
        When you place an order through the Site, we will maintain your Order
        Information for our records unless and until you ask us to delete this
        information.
      </p>
      <h4 className="mt-4">Changes</h4>
      <p>
        We may update this privacy policy from time to time in order to reflect,
        for example, changes to our practices or for other operational, legal or
        regulatory reasons.
      </p>
      <h4 className="mt-4">Minors</h4>
      <p>The Site is not intended for individuals under the age of 18.</p>
      <h4 className="mt-4">Contact us</h4>
      <p>
        For more information about our privacy practices, if you have questions,
        or if you would like to make a complaint, please contact us by e‑mail at
        support@ltl.com.
      </p>
    </Container>
  );
};

export default PrivacyPolicyScreen;
